version: '3'
networks:
  app-net:
    driver: bridge
services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017 #убрать
    networks:
      - app-net
    volumes:
      - './data:/data/db'
  nginx:
    image: nginx:latest
    ports:
      - '8090:80'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./php:/var/www
      - ./logs:/var/log/nginx
    links:
      - php
  php:
    build: ./php
    volumes:
      - ./php:/var/www
    environment:
      AMO_ID: ${AMO_ID}
      AMO_SECRET: ${AMO_SECRET}
      AMO_DOMAIN: ${AMO_DOMAIN}
      AMO_REDIRECT_URI: ${AMO_REDIRECT_URI}
